### ISSUE TITLE
Info request

### ISSUE THREAD

**Issue by dentex** [kartun83/micropython-MQ#1]
Hello!
I was trying to use a Chinese module with a MQ7 sensor onboard. Using your library I found that MicroPython complained about some syntax errors (apparently; I'm not an expert). I changed it a little bit and I issued a reading... Then I had a final error I don't know how to fix:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "BaseMQ.py", line 150, in readScaled
    ValueError: math domain error

Other than that, according to what the guys [here](https://forum.arduino.cc/index.php?topic=294085.0) were talking about, it seems that to issue a reading, the module must be powered respecting certain cycles (1,4V and 5V alternatively).

Do you have any advice in regards?
Thanks.

**Comment by NahianMugdho** [comment]
Were you able to solve your problem? I'm facing the same "Math Domain Error" problem with MQ-2.

**Comment by NahianMugdho** [comment]
> Hello! I was trying to use a Chinese module with a MQ7 sensor onboard. Using your library I found that MicroPython complained about some syntax errors (apparently; I'm not an expert). I changed it a little bit and I issued a reading... Then I had a final error I don't know how to fix:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "BaseMQ.py", line 150, in readScaled
> ValueError: math domain error
> ```
> 
> Other than that, according to what the guys [here](https://forum.arduino.cc/index.php?topic=294085.0) were talking about, it seems that to issue a reading, the module must be powered respecting certain cycles (1,4V and 5V alternatively).
> 
> Do you have any advice in regards? Thanks.

Were you able to solve your problem? I'm facing the same "Math Domain Error" problem with MQ-2.

**Comment by dentex** [comment]
I never actually used the module, sorry.
